-- -------------------------------------------------------------
-- 
-- File Name: D:\dspb_serum\hdlsrc\tmod\tmod.vhd
-- Created: 2020-03-15 21:26:58
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: tmod
-- Source Path: tmod
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY tmod IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic
        );
END tmod;


ARCHITECTURE rtl OF tmod IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Sine_Wave_out1                   : signed(13 DOWNTO 0);  -- sfix14_En12
  SIGNAL address_cnt                      : unsigned(3 DOWNTO 0) := to_unsigned(0,4);  -- ufix4

BEGIN
  enb <= clk_enable;

-- ADDRESS COUNTER
  Sine_Wave_addrcnt_temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      address_cnt <= to_unsigned(0, 4);
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF address_cnt >= to_unsigned(9, 4) THEN
          address_cnt <= to_unsigned(0, 4);
        ELSE
          address_cnt <= address_cnt + to_unsigned(1, 4);
        END IF;
      END IF;
    END IF; 
  END PROCESS Sine_Wave_addrcnt_temp_process1;

-- FULL WAVE LOOKUP TABLE
  PROCESS(address_cnt)
  BEGIN
    CASE address_cnt IS
      WHEN "0000" => Sine_Wave_out1 <= "00000000000000";
      WHEN "0001" => Sine_Wave_out1 <= "00100101101000";
      WHEN "0010" => Sine_Wave_out1 <= "00111100111000";
      WHEN "0011" => Sine_Wave_out1 <= "00111100111000";
      WHEN "0100" => Sine_Wave_out1 <= "00100101101000";
      WHEN "0101" => Sine_Wave_out1 <= "00000000000000";
      WHEN "0110" => Sine_Wave_out1 <= "11011010011000";
      WHEN "0111" => Sine_Wave_out1 <= "11000011001000";
      WHEN "1000" => Sine_Wave_out1 <= "11000011001000";
      WHEN "1001" => Sine_Wave_out1 <= "11011010011000";
      WHEN OTHERS => Sine_Wave_out1 <= "11011010011000";
    END CASE;
  END PROCESS;


END rtl;

