# This is the hw.tcl file for 'nmwtest_dut'
# Generated by Altera DSP Builder Advanced 

package require -exact qsys 14.1

# module nmwtest_dut
set_module_property NAME nmwtest_dut
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Altera DSP Builder Advanced"
set_module_property DISPLAY_NAME nmwtest_dut
set_module_property EDITABLE false

# filesets
add_fileset DSPBA_QUARTUS_SYNTH QUARTUS_SYNTH quartus_synth_callback
set_fileset_property DSPBA_QUARTUS_SYNTH TOP_LEVEL nmwtest_dut

proc quartus_synth_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "nmwtest_dut_safe_path_flat.vhd" VHDL PATH "nmwtest_dut_safe_path_flat.vhd"
	add_fileset_file "nmwtest_dut.vhd" VHDL PATH "nmwtest_dut.vhd"
	add_fileset_file "nmwtest_dut_filter1.vhd" VHDL PATH "nmwtest_dut_filter1.vhd"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm0.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm1.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm2.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm3.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm4.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm5.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm6.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm7.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm8.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm9.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm10.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm11.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm0.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm1.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm2.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm3.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm4.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm5.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm6.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm7.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm8.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm9.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm10.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm11.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm0.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm1.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm2.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm3.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm4.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm5.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm6.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm7.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm8.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm9.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm10.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm11.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm0.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm1.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm2.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm3.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm4.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm5.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm6.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm7.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm8.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm9.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm10.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm11.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm11.hex"
	add_fileset_file "nmwtest_dut_scale1.vhd" VHDL PATH "nmwtest_dut_scale1.vhd"
}
add_fileset DSPBA_SIM_VERILOG SIM_VERILOG sim_verilog_callback
set_fileset_property DSPBA_SIM_VERILOG TOP_LEVEL nmwtest_dut

proc sim_verilog_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "nmwtest_dut_safe_path_flat.vhd" VHDL PATH "nmwtest_dut_safe_path_flat.vhd"
	add_fileset_file "nmwtest_dut.vhd" VHDL PATH "nmwtest_dut.vhd"
	add_fileset_file "nmwtest_dut_filter1.vhd" VHDL PATH "nmwtest_dut_filter1.vhd"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm0.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm1.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm2.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm3.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm4.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm5.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm6.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm7.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm8.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm9.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm10.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm11.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm0.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm1.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm2.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm3.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm4.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm5.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm6.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm7.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm8.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm9.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm10.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm11.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm0.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm1.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm2.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm3.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm4.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm5.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm6.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm7.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm8.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm9.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm10.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm11.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm0.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm1.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm2.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm3.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm4.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm5.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm6.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm7.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm8.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm9.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm10.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm11.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm11.hex"
	add_fileset_file "nmwtest_dut_scale1.vhd" VHDL PATH "nmwtest_dut_scale1.vhd"
}
add_fileset DSPBA_SIM_VHDL SIM_VHDL sim_vhdl_callback
set_fileset_property DSPBA_SIM_VHDL TOP_LEVEL nmwtest_dut

proc sim_vhdl_callback {entity_name} {
	add_fileset_file "dspba_library_package.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library_package.vhd"
	add_fileset_file "dspba_library.vhd" VHDL PATH "$::env(QUARTUS_ROOTDIR)/dspba/backend/Libraries/vhdl/base/dspba_library.vhd"
	add_fileset_file "nmwtest_dut_safe_path_flat.vhd" VHDL PATH "nmwtest_dut_safe_path_flat.vhd"
	add_fileset_file "nmwtest_dut.vhd" VHDL PATH "nmwtest_dut.vhd"
	add_fileset_file "nmwtest_dut_filter1.vhd" VHDL PATH "nmwtest_dut_filter1.vhd"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm0.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm1.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm2.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm3.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm4.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm5.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm6.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm7.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm8.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm9.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm10.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo0_cm11.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo0_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm0.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm1.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm2.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm3.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm4.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm5.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm6.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm7.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm8.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm9.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm10.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo0_cm11.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo0_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm0.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm1.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm2.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm3.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm4.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm5.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm6.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm7.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm8.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm9.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm10.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u0_m0_wo1_cm11.hex" HEX PATH "nmwtest_dut_filter1_u0_m0_wo1_cm11.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm0.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm0.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm1.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm1.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm2.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm2.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm3.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm3.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm4.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm4.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm5.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm5.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm6.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm6.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm7.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm7.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm8.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm8.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm9.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm9.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm10.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm10.hex"
	add_fileset_file "nmwtest_dut_filter1_u1_m0_wo1_cm11.hex" HEX PATH "nmwtest_dut_filter1_u1_m0_wo1_cm11.hex"
	add_fileset_file "nmwtest_dut_scale1.vhd" VHDL PATH "nmwtest_dut_scale1.vhd"
}

# interfaces
# Interface clock
add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1
add_interface_port clock areset reset Input 1

# Interface bus_reset
add_interface bus_reset reset end
set_interface_property bus_reset ENABLED true
set_interface_property bus_reset ASSOCIATED_CLOCK clock
add_interface_port bus_reset h_areset reset Input 1

# Interface bus
add_interface bus avalon slave
set_interface_property bus setupTime 0
set_interface_property bus ASSOCIATED_CLOCK clock
set_interface_property bus ENABLED true
add_interface_port bus busIn_address address Input 10
add_interface_port bus busIn_write write Input 1
set_port_property busIn_write VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port bus busIn_writedata writedata Input 16

# Interface exp
add_interface exp conduit end
set_interface_property exp ENABLED true
add_interface_port exp d_0 data_d_0 Input 14
add_interface_port exp d_1 data_d_1 Input 14
add_interface_port exp v_s valid_v_s Input 1
set_port_property v_s VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp c_s channel_c_s Input 8
add_interface_port exp b_0 data_b_0 Input 1
set_port_property b_0 VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp b_1 data_b_1 Input 1
set_port_property b_1 VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp dout_0 data_dout_0 Output 14
add_interface_port exp dout_1 data_dout_1 Output 14
add_interface_port exp dout_2 data_dout_2 Output 14
add_interface_port exp dout_3 data_dout_3 Output 14
add_interface_port exp vout_s valid_vout_s Output 1
set_port_property vout_s VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port exp cout_s channel_cout_s Output 8
