// This is the memory map header file for ''
// Generated by Altera DSP Builder Advanced Flow Tools Release Version 16.1 on Mon Mar 16 22:23:12 2020

// This file contains the address of each register in the design, with the block name, 
// read/write mode, and description in the block parameters as comments for each.

// Each section denotes one ModelIP/ModelBus block and is laid out as follows:
// <block name> : <description from block>
// <REGISTER_NAME>_BIT_WIDTH <bit width from block>
// <REGISTER_NAME>_FRAC_WIDTH <frac width from block>
// <REGISTER_NAME>_PRIVATE_SPACE <is the private register space box checked?>
// Then, for each addressable word of the block:
// <REGISTER_NAME>_LSB <LSB of word>
// <REGISTER_NAME>_MSB <MSB of word>
// <REGISTER_NAME>_WIDTH <width of word>
// <REGISTER_NAME> <word address in hex format> <read/write mode>

#define AVALON_BUS_WIDTH 16
#define AVALON_ADDRESS_WIDTH 10
// nmwtest_dut_filter1 : FIR Coefficient Registers
#define NMWTEST_DUT_FILTER1_BIT_WIDTH 13
#define NMWTEST_DUT_FILTER1_FRAC_WIDTH 9
#define NMWTEST_DUT_FILTER1_PRIVATE_SPACE false
#define NMWTEST_DUT_FILTER1_LSB 0
#define NMWTEST_DUT_FILTER1_MSB 12
#define NMWTEST_DUT_FILTER1_WIDTH 13
#define NMWTEST_DUT_FILTER1_STARTADDR 0x200 // Read/Write 
#define NMWTEST_DUT_FILTER1_LENGTH 48 

